<a href="https://colab.research.google.com/github/Kalyaniruthala-30/AI_ML_Avanthi_kalyani/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,])
print(a)


[1 2 3]


In [ ]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get number of elements
a.size

3

In [15]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])
print(a)
a[1,5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


13

In [ ]:
import numpy as np

In [17]:
 b = np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
 print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [21]:
import numpy as np
np.full((2,2),99)r998tf

NameError: name 'array' is not defined